config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:show, :new, :create] do
    scope module: :user do
      resources :dashboard, only: [:index]
      resources :lists
      resources :partner_requests, only: [:create, :destroy]
      resources :partner, only: [:update]
      resources :competitions, only: [:index, :show] do
        resources :games, only: [:show]
      end
    end
  end
  resources :lists, only: [:show] do
    scope module: :list do
      resources :tasks
    end
  end
  resources :competitions, only: [:new, :create, :show] do
    scope module: :competition do
      resources :games, only: [:new, :create, :destroy]
    end
  end
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :games
  has_many :participants, through: :games
  has_many :users, through: :participants

  validates_presence_of :name
  validates_presence_of :score_type
  enum score_type: [ :wins, :points ]
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :partner, foreign_key: :partner_id, class_name: 'User', inverse_of: :partner, optional: true
  has_many :lists
  has_many :partner_requests
  has_many :participants
  has_many :games, through: :participants
  has_many :competitions, through: :games

  validates_presence_of :name
  validates :email, uniqueness: true, presence: true
  validates_presence_of :birthday
  validates_presence_of :password

  has_secure_password

  def incoming_requests_with_names
    PartnerRequest.joins(:user).where(partner_id: self.id).select('partner_requests.*, users.name as username')
  end

  def pending_request?
    pending_requests.any?
  end

  def pending_requests
    partner_requests.map do |pr|
      pr.partner
    end
  end

  def combined_lists
    if !partner.nil?
      List.joins(:user).where(user_id: [self.id, self.partner.id])
    else
      lists
    end
  end
end

app/controllers/competition/games_controller.rb
class Competition::GamesController < ApplicationController
  before_action :find_competition
  def new
    @game = @competition.games.new
  end

  def create
    @game = @competition.games.new(game_params)
    if @game.save
      Participant.create!(game: @game, user: current_user)
      flash[:notice] = "Game created. Good luck, soldier!"
      redirect_to user_competition_path(current_user, @competition)
    else
      flash[:notice] = "You forgot some information. Try again."
      render :new
    end
  end

  private
  def find_competition
    @competition = Competition.find(params[:competition_id])
  end

  private
  def game_params
    params.require(:game).permit(:name, :winning_score)
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  def new
    @competition = Competition.new
  end

  def create
    params
    @competition = Competition.new(competition_params)
    if @competition.save
      flash[:notice] = "Competition Created! Create a game to get started."
      redirect_to new_competition_game_path(@competition)
    else
      flash[:notice] = "You must've forgot some information. Try again."
      render :new
    end
  end

  private
  def competition_params
    params.require(:competition).permit(:name, :point_limit, :score_type)
  end
end

app/controllers/user/competitions_controller.rb
class User::CompetitionsController < ApplicationController
  before_action :find_competitions, only: [:index]
  before_action :find_competition, only: [:show]
  before_action :find_competition_games, only: [:show]

  def index
  end

  def show
  end

  private
  def find_competitions
    @competitions = current_user.competitions
  end

  private
  def find_competition
    @competition = Competition.find(params[:id])
  end

  def find_competition_games
    @games = @competition.games
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :find_user, only: [:index]
  before_action :find_partner, only: [:index]
  before_action :confirm_user, only: [:index]

  def index
  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end

  private
  def find_partner
    @partner = @user.partner
  end
end

app/controllers/user/lists_controller.rb
class User::ListsController < ApplicationController
  before_action :find_user
  before_action :find_user_lists
  before_action :find_list, only: [:destroy]
  before_action :confirm_user

  def index
  end

  def new
    @list = List.new
  end

  def create
    @list = @user.lists.new(list_params)
    if @list.save
      flash[:notice] = "List Created!"
      redirect_to user_lists_path(current_user)
    else
      flash[:notice] = "Please fill in a name."
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to user_lists_path(@user)
  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end

  private
  def find_user_lists
    @lists = @user.combined_lists
  end
  
  private
  def list_params
    params.require(:list).permit(:name)
  end

  private
  def find_list
    @list = List.find(params[:id])
  end
end

app/controllers/user/partner_controller.rb
class User::PartnerController < ApplicationController
  before_action :find_user_and_partner
  
  def update
    @user.update_attribute(:partner, @partner)
    @partner.update_attribute(:partner, @user)
    @partner_request.destroy_all
    flash[:notice] = "Partnership Created!"
    redirect_to user_dashboard_index_path(@user)
  end

  private
  def find_user_and_partner
    @user = User.find(params[:user_id])
    @partner = User.find(params[:id])
    @partner_request = PartnerRequest.where(user: @partner, partner: @user)
  end
end

app/controllers/user/partner_requests_controller.rb
class User::PartnerRequestsController < ApplicationController
  before_action :find_partner, only: [:create]
  before_action :find_user, only: [:create]
  def create
    if !@partner.nil?
      @user.partner_requests.create(partner: find_partner)
      flash[:notice] = "Partner Request submitted! Waiting on their approval."
    else
      flash[:notice] = "Email Not found, could not submit your request."
    end
    redirect_to user_dashboard_index_path(current_user)
  end

  private
  def find_partner
    @partner = User.where(email: params[:partner_email]).first
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New account created, Welcome to NoodleHub!"
      redirect_to user_dashboard_index_path(@user)
      session[:user_id] = @user.id
    else
      flash[:notice] = "Couldn't create your new account, maybe you forgot some information?"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :birthday, :email, :password)
  end
end

app/views/user/competitions/index.html.erb
<body>
  <div class="card-columns" id="competitions">
    <% @competitions.each do |competition| %>
      <div class="card">
        <div class="card text-center" id="competition-<%= competition.id %>">
          <div class="card-body">
            <div class="card-title btn-group dropend">
              <%= button_to "#{competition.name}", user_competition_path(current_user.id, competition.id), method: :get, class: "btn" %>
              <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Delete", competition_path(competition), method: :delete, class: "dropdown-item text-strong" %></li>
                <li><%= %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</body>

app/views/user/competitions/show.html.erb
<body>
  <div class="card-columns">
    <% @games.each do |game| %>
      <div class="card">
        <div class="card text-center">
          <div class="card-body">
            <div class="card-title btn-group dropend">
              <%= button_to "#{game.name}", user_competition_game_path(current_user.id, @competition.id, game.id), method: :get, class: "btn" %>
              <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Delete", competition_game_path(@competition.id, game.id), method: :delete, class: "dropdown-item text-strong" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</body>