config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:show, :new, :create] do
    scope module: :user do
      resources :dashboard, only: [:index]
      resources :lists
      resources :partner_requests, only: [:create, :destroy]
      resources :partner, only: [:update]
      resources :competitions, only: [:index, :show] do
        resources :games, only: [:show]
      end
    end
  end
  resources :lists, only: [:show] do
    scope module: :list do
      resources :tasks
    end
  end
  resources :competitions, only: [:new, :create, :show] do
    scope module: :competition do
      resources :games, only: [:new, :create, :destroy]
    end
  end
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_tasks, dependent: :destroy
  has_many :tasks, through: :list_tasks
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :partner, foreign_key: :partner_id, class_name: 'User', inverse_of: :partner, optional: true
  has_many :lists
  has_many :partner_requests
  has_many :participants
  has_many :games, through: :participants
  has_many :competitions, through: :games

  validates_presence_of :name
  validates :email, uniqueness: true, presence: true
  validates_presence_of :birthday
  validates_presence_of :password

  has_secure_password

  def incoming_requests_with_names
    PartnerRequest.joins(:user).where(partner_id: self.id).select('partner_requests.*, users.name as username')
  end

  def pending_request?
    pending_requests.any?
  end

  def pending_requests
    partner_requests.map do |pr|
      pr.partner
    end
  end

  def combined_lists
    if !partner.nil?
      List.joins(:user).where(user_id: [self.id, self.partner.id])
    else
      lists
    end
  end
end

app/controllers/list/tasks_controller.rb
class List::TasksController < ApplicationController
  before_action :find_list
  before_action :find_list_user, only: [:create, :update, :destroy]
  before_action :find_task, only: [:edit, :update, :destroy]
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      ListTask.create!(list: @list, task: @task)
      flash[:notice] = "Task Created!"
      redirect_to user_lists_path(current_user)
    else
      flash[:notice] = "You forgot to provide some information."
      render :new
    end
  end

  def edit
  end

  def update
    @task.update_attributes(task_params)
    @task.save
    redirect_to user_lists_path(current_user)
  end

  def destroy
    @task.destroy
    redirect_to user_lists_path(current_user)
  end

  private
  def find_list
    @list = List.find(params[:list_id])
  end

  private
  def find_list_user
    @user = @list.user
  end

  private
  def task_params
    params.require(:task).permit(:name, :description, :due, :status)
  end

  private
  def find_task
    @task = Task.find(params[:id])
  end
end

app/controllers/user/competitions_controller.rb
class User::CompetitionsController < ApplicationController
  before_action :find_competitions, only: [:index]
  before_action :find_competition, only: [:show]
  before_action :find_competition_games, only: [:show]

  def index
  end

  def show
  end

  private
  def find_competitions
    @competitions = current_user.competitions
  end

  private
  def find_competition
    @competition = Competition.find(params[:id])
  end

  def find_competition_games
    @games = @competition.games
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :find_user, only: [:index]
  before_action :find_partner, only: [:index]
  before_action :confirm_user, only: [:index]

  def index
  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end

  private
  def find_partner
    @partner = @user.partner
  end
end

app/controllers/user/lists_controller.rb
class User::ListsController < ApplicationController
  before_action :find_user
  before_action :find_user_lists
  before_action :find_list, only: [:destroy]
  before_action :confirm_user

  def index
  end

  def new
    @list = List.new
  end

  def create
    @list = @user.lists.new(list_params)
    if @list.save
      flash[:notice] = "List Created!"
      redirect_to user_lists_path(current_user)
    else
      flash[:notice] = "Please fill in a name."
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to user_lists_path(@user)
  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end

  private
  def find_user_lists
    @lists = @user.combined_lists
  end
  
  private
  def list_params
    params.require(:list).permit(:name)
  end

  private
  def find_list
    @list = List.find(params[:id])
  end
end

app/controllers/user/partner_controller.rb
class User::PartnerController < ApplicationController
  before_action :find_user_and_partner
  
  def update
    @user.update_attribute(:partner, @partner)
    @partner.update_attribute(:partner, @user)
    @partner_request.destroy_all
    flash[:notice] = "Partnership Created!"
    redirect_to user_dashboard_index_path(@user)
  end

  private
  def find_user_and_partner
    @user = User.find(params[:user_id])
    @partner = User.find(params[:id])
    @partner_request = PartnerRequest.where(user: @partner, partner: @user)
  end
end

app/controllers/user/partner_requests_controller.rb
class User::PartnerRequestsController < ApplicationController
  before_action :find_partner, only: [:create]
  before_action :find_user, only: [:create]
  def create
    if !@partner.nil?
      @user.partner_requests.create(partner: find_partner)
      flash[:notice] = "Partner Request submitted! Waiting on their approval."
    else
      flash[:notice] = "Email Not found, could not submit your request."
    end
    redirect_to user_dashboard_index_path(current_user)
  end

  private
  def find_partner
    @partner = User.where(email: params[:partner_email]).first
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New account created, Welcome to NoodleHub!"
      redirect_to user_dashboard_index_path(@user)
      session[:user_id] = @user.id
    else
      flash[:notice] = "Couldn't create your new account, maybe you forgot some information?"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :birthday, :email, :password)
  end
end

app/views/user/lists/index.html.erb
<header>
  <h2 class="welcome-header center-align text-secondary"><b><i>Lists</i></b></h2>
  <div class="center-align">
    <%= button_to "Create a List", new_user_list_path, method: :get, class: "btn btn-outline-secondary" %>
  </div>
</header><hr>

<body>
  <div class="card-columns" id="lists">
    <% @lists.each do |list| %>
      <div class="card">
        <div class="card text-center" id="list-<%= list.id %>">
          <div class="card-body">
            <div class="card-title btn-group dropend">
              <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <b><i><%= list.name %></i></b>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Create A Task", new_list_task_path(list), class: "dropdown-item text-success" %></li>
                <div class="dropdown-divider"></div>
                <li><%= link_to "Edit", edit_user_list_path(@user, list), class: "dropdown-item text-secondary"%></li>
                <li><%= link_to "Delete", user_list_path(@user, list), method: :delete, class: "dropdown-item text-danger" %></li>
              </ul>
            </div>
            <div id="list-<%= list.id %>-incomplete">
              <% list.tasks.each do |task| %>
                <% if task.incomplete? %>
                  <div class="btn-group dropright card-body col" id="task-<%= task.id %>">
                    <button type="button" class="btn dropdown text-danger" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= task.name %>
                    </button>
                    <div class="dropdown-menu" id="task-<%= task.id %>-dropdown">
                      <li class="dropdown-item"><b><i><%= task.description %></i></b></li>
                      <li class="dropdown-item disabled text-danger"><b><i><%= task.due %></i></b></li>
                      <div class="dropdown-divider"></div>
                      <%= link_to "Edit", edit_list_task_path(list, task), class: "dropdown-item text-secondary" %>
                      <%= link_to "Complete", list_task_path(list, task, task: {status: 'complete'}), method: :patch, class: "dropdown-item text-success" %>
                      <%= link_to "Remove", list_task_path(list, task), method: :delete, class: "dropdown-item text-danger" %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div><hr>
            <div id="list-<%= list.id %>-complete">
              <% list.tasks.each do |task| %>
                <% if task.complete? %>
                  <div class="btn-group dropright card-body col">
                    <button type="button" class="btn dropdown text-success" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= task.name %>
                    </button>
                    <div class="dropdown-menu">
                      <li class="dropdown-item"><b><i><%= task.description %></i></b></li>
                      <li class="dropdown-item text-danger"><b><i>Due: <%= task.due %></i></b></li>
                      <div class="dropdown-divider"></div>
                      <%= link_to "Edit", edit_list_task_path(list, task), class: "dropdown-item text-secondary" %>
                      <%= link_to "Incomplete", list_task_path(list, task, task: {status: 'incomplete'}), method: :patch, class: "dropdown-item text-warning" %>
                      <%= link_to "Remove", list_task_path(list, task), method: :delete, class: "dropdown-item text-danger" %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>  
          <div class="card-footer text-muted text-right">
            <small><i>created by <%= list.user.name %></i></small>
          </div>
        </div>  
      </div>
    <% end %>
  </div>
</body>

app/views/user/lists/new.html.erb
<body>
  <div class="center-align">
    <section class="container">
      <div class="jumbotron bg-light center-align shadow p-3 mb-5 bg-white rounded">
        <h3 class="welcome-header"><i>New List:</i></h3>
        <%= form_with model: @list, url: user_lists_path(@user), local: :true do |f| %>
          <%= f.text_field :name, placeholder: "name", class: "center-align" %> <br><br>
          <%= f.submit :create, class: "bg-secondary text-white" %>
        <% end %>
      </div>
    </section>
  </div>
</body>