config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:show, :new, :create] do
    scope module: :user do
      resources :dashboard, only: [:index]
      resources :lists
      resources :partner_requests, only: [:create, :destroy]
      resources :partner, only: [:update]
      resources :competitions, only: [:index, :show] do
        resources :games, only: [:show]
      end
    end
  end
  resources :lists, only: [:show] do
    scope module: :list do
      resources :tasks
    end
  end
  resources :competitions, only: [:new, :create, :show] do
    scope module: :competition do
      resources :games, only: [:new, :create, :destroy]
    end
  end
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <head>
    <title>Coupl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
  </head>
  <header>
      <nav class="navbar navbar-dark">
        <h4 class="center-align shadow-text"><b><i><%= link_to "Coupl", root_path %></i></b></h4>
        <% if logged_in? %>
          <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to "Dashboard", user_dashboard_index_path(current_user), class: "dropdown-item text-dark" %>
              <%= link_to "Lists", user_lists_path(current_user), class: "dropdown-item text-secondary" %>
              <%= link_to "Competitions", user_competitions_path(current_user), class: "dropdown-item text-secondary" %>
              <div class="dropdown-divider"></div>
              <li><%= link_to "Log Out", logout_path, method: :delete, class: "dropdown-item text-dark" %></li>
            </div>
          </div>
        <% end %>
      </nav>
  </header>

  <body>
    <% flash.each do |type, message| %>
    <div class="alert alert-danger center-align">
        <b><%= message %></b>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>